-- AlterTable
ALTER TABLE "Price" ALTER COLUMN "regular" SET DATA TYPE BIGINT,
ALTER COLUMN "childrenMovie" SET DATA TYPE BIGINT,
ALTER COLUMN "newRelease" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "Rent" ALTER COLUMN "noOfDays" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "Video" ALTER COLUMN "maxAge" SET DATA TYPE BIGINT,
ALTER COLUMN "yearReleased" SET DATA TYPE BIGINT;
